name: Run Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests on ./nextdns-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.24.12'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./nextdns-go -v
