name: Run Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Use secrets.NEXTDNS_API_TOKEN if present
      - name: Set NextDNS API Token from GitHub Secrets
        if: ${{ secrets.NEXTDNS_API_TOKEN != '' }}
        run: |
          echo "NEXTDNS_API_TOKEN=${{ secrets.NEXTDNS_API_TOKEN }}" >> "$GITHUB_ENV"

      # Otherwise attempt to load via 1Password
      - name: Load NextDNS API Token
        if: ${{ secrets.NEXTDNS_API_TOKEN == '' }}
        uses: 1password/load-secrets-action@v3
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          NEXTDNS_API_TOKEN: ${{ secrets.OP_NEXTDNS_API_TOKEN_REF }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.24.12'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        if: env.NEXTDNS_API_TOKEN != ''
        run: |
          NEXTDNS_API_TOKEN=$NEXTDNS_API_TOKEN go test -tags integration
