name: Run Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests on ./nextdns-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Load secret
        id: load_secrets
        uses: 1password/load-secrets-action@v3
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: "op://Service/waw6ozs2rl3wckef47kk2ieazi/credential"
      #          OP_ENV_FILE: "./path/to/.env.tpl" # see tests/.env.tpl for example

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.24.12'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          cd ./integration
          NEXTDNS_API_TOKEN=${{ steps.load_secrets.outputs.SECRET }} go test -tags integration
