// Code generated by go generate; DO NOT EDIT.

package models

import "encoding/json"

func (p Denylist) String() string {
	type Alias Denylist
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}
