// Code generated by go generate; DO NOT EDIT.

package models

import "encoding/json"

func (p ParentalControlRecreationInterval) String() string {
	type Alias ParentalControlRecreationInterval
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p ParentalControlRecreation) String() string {
	type Alias ParentalControlRecreation
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p ParentalControlCategories) String() string {
	type Alias ParentalControlCategories
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p ParentalControlServices) String() string {
	type Alias ParentalControlServices
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}
