// Code generated by go generate; DO NOT EDIT.

package models

import "encoding/json"

func (p Privacy) String() string {
	type Alias Privacy
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p PrivacyBlocklists) String() string {
	type Alias PrivacyBlocklists
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p PrivacyNatives) String() string {
	type Alias PrivacyNatives
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}
