// Code generated by go generate; DO NOT EDIT.

package models

import "encoding/json"

func (p Settings) String() string {
	type Alias Settings
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p SettingsBlockPage) String() string {
	type Alias SettingsBlockPage
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p SettingsLogsDrop) String() string {
	type Alias SettingsLogsDrop
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p SettingsLogs) String() string {
	type Alias SettingsLogs
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}

func (p SettingsPerformance) String() string {
	type Alias SettingsPerformance
	c, err := json.MarshalIndent(&struct {
		Alias
	}{
		Alias: Alias(p),
	}, "", "    ")
	if err != nil {
		return "<invalid json>"
	}
	return string(c)
}
